---
argument_specs:
  main:
    short_description: Explicitly prune unused Docker resources
    options:
      docker_maintenance_prune_containers:
        type: bool
        default: false

      docker_maintenance_prune_images:
        type: bool
        default: false

      docker_maintenance_prune_networks:
        type: bool
        default: false

      docker_maintenance_prune_volumes:
        type: bool
        default: false

      docker_maintenance_prune_builder_cache:
        type: bool
        default: false

      docker_maintenance_containers_filters:
        type: dict
        default:
          until: 168h

      docker_maintenance_images_filters:
        type: dict
        default:
          dangling: true

      docker_maintenance_networks_filters:
        type: dict
        default: {}

      docker_maintenance_volumes_filters:
        type: dict
        default: {}

      docker_maintenance_builder_cache_filters:
        type: dict
        default: {}
