---
# Deployment-specific agents runtime instances.
docker_s4u_agents_runtime_instances: []
docker_s4u_agents_runtime_cleanup_stale_instances: false

docker_s4u_agents_runtime_config_container_path: "/app/config"
docker_s4u_agents_runtime_config_cleanup: true
docker_s4u_agents_runtime_tmpfs:
  - "/tmp:rw,noexec,nosuid,nodev,size=32m"
